from .nodes.lora_remap_anima import (
    NODE_CLASS_MAPPINGS as _LORA_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _LORA_NODE_DISPLAY_NAME_MAPPINGS,
)
from .nodes.model_merge_anima import (
    NODE_CLASS_MAPPINGS as _MERGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as _MERGE_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **_LORA_NODE_CLASS_MAPPINGS,
    **_MERGE_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **_LORA_NODE_DISPLAY_NAME_MAPPINGS,
    **_MERGE_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
